- hosts: masters
  become: true
  vars_files:
    - env_vars
  tasks:
    - name: Pulling images required for setting up a Kubernetes cluster
      shell: kubeadm config images pull

    - name: initialise/start the cluster
      shell:  kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
      args:
        chdir: $HOME
      async: 30
      poll: 60

    - name: Configure the initialised  kubernetes master
      shell:   mkdir -p $HOME/.kube &&  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config &&  sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Apply a calico manifset to init the pod network
      become: true
      become_user: ansible
      shell: sudo kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME
    - name: Get the join command to be used by the worker
      become: true
      become_user: ansible 
      shell: sudo kubeadm token create  --print-join-command
      register: kube_join_command

    - name: Save the join command to a local file
      become: true
      local_action: copy content="{{ kube_join_command.stdout_lines[0] }}" dest="/etc/kube_join_command" mode=0777
